package com.example.smartwardrobe.data.model

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

/**
 * Wardrobe item representing a single piece of clothing
 * @property id Firestore document ID
 * @property userId Owner's Firebase Auth UID
 * @property name Item name (e.g., "Blue Jeans", "White T-Shirt")
 * @property category Category enum (TOP, BOTTOM, SHOES, etc.)
 * @property color Primary color of the item
 * @property brand Brand name (optional)
 * @property size Size (e.g., "M", "L", "32")
 * @property imageUrl URL to the item's photo in Firebase Storage
 * @property ai3DModelUrl URL to the 3D model generated by AI (optional, for future integration)
 * @property tags Custom tags for organization (e.g., "casual", "formal", "summer")
 * @property createdAt Item creation timestamp
 * @property updatedAt Last update timestamp
 */
data class WardrobeItem(
    @DocumentId
    val id: String = "",
    val userId: String = "",
    val name: String = "",
    val category: ClothingCategory = ClothingCategory.OTHER,
    val color: String = "",
    val brand: String? = null,
    val size: String = "",
    val imageUrl: String = "",
    val ai3DModelUrl: String? = null,
    val tags: List<String> = emptyList(),
    @ServerTimestamp
    val createdAt: Date? = null,
    @ServerTimestamp
    val updatedAt: Date? = null
)

/**
 * Clothing categories for wardrobe organization
 */
enum class ClothingCategory {
    TOP,           // Shirts, blouses, sweaters
    BOTTOM,        // Pants, skirts, shorts
    DRESS,         // Dresses, jumpsuits
    OUTERWEAR,     // Jackets, coats
    SHOES,         // All footwear
    ACCESSORIES,   // Bags, jewelry, belts
    OTHER          // Miscellaneous items
}
